### ISSUE TITLE
sg200x: the pinmux tables are incomplete

### ISSUE THREAD

**Issue by dzamlo** [sophgo/sophgo-doc#131] opened 2024-07-01 13:33 UTC
For example, the pin XGPIOB[14] is missing.

**Comment by unicornx** [comment] 2024-07-01 23:38
> For example, the pin XGPIOB[14] is missing.

Can you please details the problem, in what product and in what section?  We have separated TRM for SG2002 and SG2000.

I double checked the document, seems the problem is in section "10.1.2 FMUX Registers Description" for SG2000, and it lacks some pin definition. I compare with the pin out xls sheet @ <https://github.com/sophgo/sophgo-hardware/blob/master/SG200X/03_SG2000/04_SG2000_PINOUT.xlsx>
Is this the problem?

**Comment by dzamlo** [comment] 2024-07-02 08:22
Yes this is the problem i'm talking about.

Also, I wasn't aware of the xls document. It may be worth it to mention it in the manual.

**Comment by unicornx** [comment] 2024-07-02 23:51
> Yes this is the problem i'm talking about.
> 
> Also, I wasn't aware of the xls document. It may be worth it to mention it in the manual.

Yes, actually the content of pinmux info in TRM is from that xls sheet, and seems something are missed for sg2000. 

Directly providing the link to xls doc in TRM may be a better idea, we are considering do like this.

**Comment by unicornx** [comment] 2024-07-05 09:30
Fixed with commit: a69a1c4.

We have released v1.01 to include this change.

https://github.com/sophgo/sophgo-doc/releases/tag/sg2002-trm-v1.01
https://github.com/sophgo/sophgo-doc/releases/tag/sg2000-trm-v1.01

**Closed by unicornx** 2024-07-05 09:30 UTC
Labels: bug, SG200X
